"""added new coloumn in product

Revision ID: 08c6f6f775f1
Revises: 9dbad70c6e54
Create Date: 2026-05-20 17:00:21.636623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c6f6f775f1'
down_revision: Union[str, Sequence[str], None] = '9dbad70c6e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'brand')
    # ### end Alembic commands ###
