"""add order and item tables

Revision ID: 0e127f86dce7
Revises: 64bc00826278
Create Date: 2026-05-17 11:08:33.884057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e127f86dce7'
down_revision: Union[str, Sequence[str], None] = '64bc00826278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_mode', sa.Enum('UPI', 'CASH', 'CARD', name='paymentmethod'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.Enum('DONE', 'PENDING', name='paymentstatus'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_order_id'), 'order', ['order_id'], unique=False)
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_status', sa.Enum('TRANSIT', 'PENDING', 'DISPATCHED', 'DELIVERED', 'DELAYED', 'OUT_FOR_DELIVERY', 'FAILED', name='deliverystatus'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_item_item_id'), 'item', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_item_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_order_order_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
