"""create multiple tables

Revision ID: 260943abb50c
Revises: 
Create Date: 2026-04-26 15:51:44.521600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '260943abb50c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_product_id'), 'product', ['product_id'], unique=False)
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_table('products')
    op.drop_constraint(op.f('customer_email_key'), 'customer', type_='unique')
    op.drop_constraint(op.f('customer_phone_number_key'), 'customer', type_='unique')
    op.drop_constraint(op.f('customer_username_key'), 'customer', type_='unique')
    op.drop_constraint(op.f('customer_user_id_fkey'), 'customer', type_='foreignkey')
    op.create_foreign_key(None, 'customer', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('customer', 'hashed_password')
    op.drop_column('customer', 'phone_number')
    op.drop_column('customer', 'email')
    op.drop_column('customer', 'username')
    op.drop_constraint(op.f('seller_email_key'), 'seller', type_='unique')
    op.drop_constraint(op.f('seller_username_key'), 'seller', type_='unique')
    op.drop_column('seller', 'hashed_password')
    op.drop_column('seller', 'phone_number')
    op.drop_column('seller', 'email')
    op.drop_column('seller', 'username')
    op.add_column('user', sa.Column('user_role', sa.Enum('CUSTOMER', 'ADMIN', 'SELLER', name='userrole'), nullable=False))
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', postgresql.ENUM('CUSTOMER', 'ADMIN', 'SELLER', name='userrole'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'username')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'email')
    op.drop_column('user', 'user_role')
    op.add_column('seller', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('seller', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('seller', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('seller', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('seller_username_key'), 'seller', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('seller_email_key'), 'seller', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('customer', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('customer', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('customer', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('customer', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.create_foreign_key(op.f('customer_user_id_fkey'), 'customer', 'user', ['user_id'], ['user_id'])
    op.create_unique_constraint(op.f('customer_username_key'), 'customer', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('customer_phone_number_key'), 'customer', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('customer_email_key'), 'customer', ['email'], postgresql_nulls_not_distinct=False)
    op.create_table('products',
    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], name=op.f('products_seller_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.drop_index(op.f('ix_product_product_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
