"""added new table for black listed tokens

Revision ID: 49a42463ab29
Revises: 08c6f6f775f1
Create Date: 2026-05-21 23:19:56.705694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a42463ab29'
down_revision: Union[str, Sequence[str], None] = '08c6f6f775f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expToken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encoded_string', sa.Text(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expToken_encoded_string'), 'expToken', ['encoded_string'], unique=True)
    op.create_index(op.f('ix_expToken_id'), 'expToken', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expToken_id'), table_name='expToken')
    op.drop_index(op.f('ix_expToken_encoded_string'), table_name='expToken')
    op.drop_table('expToken')
    # ### end Alembic commands ###
