"""added description in product table

Revision ID: 9dbad70c6e54
Revises: 0e127f86dce7
Create Date: 2026-05-17 11:15:14.917156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dbad70c6e54'
down_revision: Union[str, Sequence[str], None] = '0e127f86dce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.String(), nullable=False))
    op.alter_column('product', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
